"""Add models Posts, Comments, fixed models Users, Blogs

Revision ID: 250513ca01b8
Revises: bf41f2c4e115
Create Date: 2023-09-01 18:17:25.280188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250513ca01b8'
down_revision: Union[str, None] = 'bf41f2c4e115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'owner_id')
    # ### end Alembic commands ###
