"""added field for models Blog and Post and Comments

Revision ID: 2b19a6cff2f2
Revises: 3bc210f1a542
Create Date: 2023-09-08 16:42:51.362367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b19a6cff2f2'
down_revision: Union[str, None] = '3bc210f1a542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_posts_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['posts_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_posts_id_fkey', 'comments', 'posts', ['posts_id'], ['id'])
    # ### end Alembic commands ###
