"""added field for models Blog and Post

Revision ID: 3bc210f1a542
Revises: 357260ce1904
Create Date: 2023-09-08 16:39:55.726747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc210f1a542'
down_revision: Union[str, None] = '357260ce1904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_blog_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_blog_id_fkey', 'posts', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###
