"""add field in model posts

Revision ID: 8394dc14c909
Revises: 1d2623f41249
Create Date: 2023-09-04 18:09:58.153842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8394dc14c909'
down_revision: Union[str, None] = '1d2623f41249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'blog_id')
    # ### end Alembic commands ###
