"""Added a new field for model User

Revision ID: f79e0cc5260a
Revises: 2b19a6cff2f2
Create Date: 2023-10-11 16:46:35.068181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79e0cc5260a'
down_revision: Union[str, None] = '2b19a6cff2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), server_default=sa.text("'default@email.com'"), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), server_default=sa.text('123'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
